<a href="https://colab.research.google.com/github/Asifkhan154/Asifkhan15/blob/main/prectish_numpay_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

the start NumPy import numpay as np

In [ ]:
import numpy as  np

# make the array list
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr1.ndim

1

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
arr1.size

11

In [ ]:
arr1.lenth

AttributeError: 'numpy.ndarray' object has no attribute 'lenth'

In [ ]:
arr1.itemsize

8

In [ ]:
arr1.max

<function ndarray.max>

In [ ]:
arr1.min

<function ndarray.min>

In [ ]:
arr1.shape

(11,)

In [ ]:
arr1.dtype

dtype('int64')

2D array

In [ ]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2[0][0]


np.int64(1)

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
np.median(arr2)

np.float64(5.0)

In [ ]:
np.dtype

numpy.dtype

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr2.itemsize

8

In [ ]:
arr2.shape

(3, 3)

In [ ]:
arr2.ndim

2

In [ ]:
arr2.size

9

3D array

In [ ]:
arr3=np.array([[[3,5],
                 [2,5],

                 [5,6],
                 [9,9]]])
arr3

array([[[3, 5],
        [2, 5],
        [5, 6],
        [9, 9]]])

In [ ]:
arr3.dtype

dtype('int64')

In [ ]:
arr3.size

8

In [ ]:
arr3.itemsize

8

4D array

In [ ]:
arr4=np.array([[[3,5],
                 [8,9]],

                [[9,8],
                 [10,12]],

                [[9,2],
                [3,8]]])
arr4

array([[[ 3,  5],
        [ 8,  9]],

       [[ 9,  8],
        [10, 12]],

       [[ 9,  2],
        [ 3,  8]]])

In [ ]:
arr4.ndim

3

In [ ]:
arr4.size

12

In [ ]:
arr4.dtype

dtype('int64')

In [ ]:
arr4.shape

(3, 2, 2)

slicing-> yeh ek cak ki trha hota hai  jitn ahame jarurat hoti hai utna hi use kerte hai jaise [1,2,3,4,5] ab hme 2 se 4 tka value chiye ise ham slicing khate hai ese use kerne ka tarika hai  = arr1.[2:4] to ye output dega 2,3,4

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

by defult
strating_index =0 endinng_index=n septep size=1

In [ ]:
arr1[::2]

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
subarray=arr2[0:2,2:0]

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr1[::2]

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr1[::5]

array([ 1,  6, 11])

In [ ]:
arr1[::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr1[2:2]

array([], dtype=int64)

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.size

11

In [ ]:
arr1.itemsize

8

sorted array => isme koi sankhaya karam me hoti hai to se disandinng ker diya jaat hai or ager disanding ho to assandig me ker diya jaata hai  for example - > [1,2,3,4,5,6], 2   [5,7,8,6,2,1,0,3,4]

In [ ]:
arr6=np.array([5,7,8,6,2,1,0,3,4])
sorted_arr6=np.sort(arr6)
sorted_arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
sorted_indices=np.argsort(arr6)
print(sorted_indices)


[6 5 4 7 8 0 3 1 2]


In [ ]:
# rows wise kerte hai

arr6=np.array([[[3,2,1],
               [5,6,7]]])

sorted_arr6=np.sort(arr6)
sorted_arr6

array([[[1, 2, 3],
        [5, 6, 7]]])

In [ ]:
#axis=0 ka kamm column ke lana wsie kaam kerna hota hai (axis=0)

sorted_arr6=np.sort(arr6,axis=0)
sorted_arr6

array([[[3, 2, 1],
        [5, 6, 7]]])

concatanating array ka matlab kisi to alag allag kaam ko jodna jai

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

result=np.concatenate((arr1,arr2))
print(result)

[1 2 3 4 5 6]


resabing array => akkar dena 1D 2D 3D array estrha ke aakr dena simple likhne ke baad

In [ ]:
arr_1D = np.array([0,1,2,3,4,5,6,7,8,9,10,11]) # 1 D array
arr_2D = arr_1D.reshape (4, 3) # 2d array
arr_2D


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
arr_3D=arr_1D.reshape(2,3,2)
arr_3D

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
arr_4D=arr_1D.reshape(6,1,2)
arr_4D

array([[[ 0,  1]],

       [[ 2,  3]],

       [[ 4,  5]],

       [[ 6,  7]],

       [[ 8,  9]],

       [[10, 11]]])

flattended array=> 1D array 2D array ko jode dena ya - kerdana yahi kaam hota hai

In [ ]:
flattened=arr_2D.reshape(-1)
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


splitting array => todna hota hai joint array ko alg alg kerd ena jaie ([1,2,3,4]) to split se [1,2]  [3,4] es trha se

In [ ]:

arr6=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=np.split(arr6,3)
print(new_arr)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


statical operator -> 2D array ko rkha or check kiya mean diian mode ye nikala jata hai ye mathmatical consept se ata hai

In [ ]:
arr=np.array ([[1,2,3],
               [4,5,6]])
mean=np.mean(arr)
print(mean)

3.5


In [ ]:
median = np.median(arr)
print(median)


3.5


In [ ]:
type(median)

numpy.float64

In [ ]:
np.std(arr)

np.float64(1.707825127659933)

In [ ]:
print(np.sum(arr))

21


data creatation  ->  ye use hota hai image processing me or machin learning graph banne me en jghao pe kaam  kerne ke liye hota hai  ye alag alga numbro ko joden pe pahle se jitna ansswer ayega uski jgha kahli bna leta hai taki system hang na kre


In [ ]:
a=np.zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]


In [ ]:
b=np.zeros((3,8))
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
c=np.zeros((3,6,8))
print(c)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


In [ ]:
d=np.ones((2,4,3))
print(d)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
e=np.full(4,10)
print(e)

[10 10 10 10]


In [ ]:
f=np.full((5,8),9.5)
print(f)

[[9.5 9.5 9.5 9.5 9.5 9.5 9.5 9.5]
 [9.5 9.5 9.5 9.5 9.5 9.5 9.5 9.5]
 [9.5 9.5 9.5 9.5 9.5 9.5 9.5 9.5]
 [9.5 9.5 9.5 9.5 9.5 9.5 9.5 9.5]
 [9.5 9.5 9.5 9.5 9.5 9.5 9.5 9.5]]


In [ ]:
type(f)

numpy.ndarray

In [ ]:
np.size

<function size at 0x78a3da537f70>

identy metrix->